// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gJWCBXid4yHZnINqmY66ZSW15iv8PYM',
    appId: '1:625390164723:web:0382c35ea1df0050543586',
    messagingSenderId: '625390164723',
    projectId: 'chatapp-d6934',
    authDomain: 'chatapp-d6934.firebaseapp.com',
    storageBucket: 'chatapp-d6934.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-gAwmz9AHlxqnc3vhDFUWtNksInOlCg',
    appId: '1:625390164723:android:2b34a45c308b9b90543586',
    messagingSenderId: '625390164723',
    projectId: 'chatapp-d6934',
    storageBucket: 'chatapp-d6934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPREd6Lcrh5EPjqOKCuSMW1wW-Eu3Ujw',
    appId: '1:625390164723:ios:5b6cce2813aea49e543586',
    messagingSenderId: '625390164723',
    projectId: 'chatapp-d6934',
    storageBucket: 'chatapp-d6934.appspot.com',
    iosBundleId: 'com.example.securechatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPREd6Lcrh5EPjqOKCuSMW1wW-Eu3Ujw',
    appId: '1:625390164723:ios:e377768535d8deef543586',
    messagingSenderId: '625390164723',
    projectId: 'chatapp-d6934',
    storageBucket: 'chatapp-d6934.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
